
#define DATA_DIRECTORY "./data"

#define MS_UPDATE_STEP 200

#define SIDE_MAP_METERS 8000

#define LEN_NAME 100
#define LEN_USER 100
#define LEN_PASS 100
#define LEN_TOKEN 30
#define LEN_URI 500

#define MAX_PLAYERS_BY_EQUIP 50
#define EQUIPS 3
#define MAX_BUILDINGS_PLAYER 200
#define MAX_UNITS_PLAYER 200

#define RADIO_ZONE_EQUIP 1800.0f

#define INIT_MINERAL_PLAYER 250
#define INIT_OIL_PLAYER 0

#define MAX_MINERALS_MAP 8000
#define MAX_AMOUNT_MINERAL_BY_ONE 500
#define MIN_AMOUNT_MINERAL_BY_ONE 250
#define AMOUNT_MINERALS_BY_BASE 10
#define MAX_MINERALS_BY_CUMULO 10
#define MIN_MINERALS_BY_CUMULO 5
#define RADIO_CUMULO_MINERALS 40
#define MS_TO_NEW_MINERAL 1700
#define RADIO_INIT_BASE_ZONE 60

#define DISTANCE_LIMIT_FIND_ANOTHER_MINERAL_RECOLECTOR 150.0f
#define DISTANCE_LIMIT_FIND_BASE_RECOLECTOR 2000.0f
#define AMOUNT_RECOLLECT_BY_SECOND_RECOLECTOR 3.0f
#define AMOUNT_BUILD_BY_SECOND_RECOLECTOR 12.0f
#define MS_UNIT_STUCK 3000
#define EPSILON_DISTANCE 0.0001f
#define MAX_PATH_MOVE_UNIT 500

#define AMOUNT_MAKE_BY_SECOND_BASE 2.0f
#define AMOUNT_MAKE_BY_SECOND_BARRACA 2.0f

#define MAX_AMOUNT_RECOLLECT_RECOLECTOR 20.0f
#define VISIBILITY_DISTANCE 60.0f


#define MINERALS_COST_BASE 500
#define MINERALS_COST_BARRACA 400
#define MINERALS_COST_TORRETA 300
#define MINERALS_COST_RECOLECTOR 70
#define MINERALS_COST_SOLDADO_RASO 100
#define MINERALS_COST_SOLDADO_ENTRENADO 200
#define MINERALS_COST_SOLDADO_TANQUE 300
#define MINERALS_COST_SOLDADO_TANQUE_PESADO 400

#define MIN_DISTANCE_TO_ATTACK_SOLDADORASO 20.0f
#define MIN_DISTANCE_TO_ATTACK_SOLDADOENTRENADO 25.0f
#define MIN_DISTANCE_TO_ATTACK_TANQUE 30.0f
#define MIN_DISTANCE_TO_ATTACK_TANQUEPESADO 35.0f
#define MIN_DISTANCE_TO_ATTACK_TORRETA 50.0f

#define AMOUNT_DAMAGE_SOLDADORASO 10.0f
#define AMOUNT_DAMAGE_SOLDADOENTRENADO 15.0f
#define AMOUNT_DAMAGE_TANQUE 25.0f
#define AMOUNT_DAMAGE_TANQUEPESADO 40.0f 
#define AMOUNT_DAMAGE_TORRETA 50.0f 

#define EVERY_MS_TO_ATTACK_SOLDADORASO 1000
#define EVERY_MS_TO_ATTACK_SOLDADOENTRENADO 1500
#define EVERY_MS_TO_ATTACK_TANQUE 2000
#define EVERY_MS_TO_ATTACK_TANQUEPESADO 4000
#define EVERY_MS_TO_ATTACK_TORRETA 3000

#define VEL_RECOLECTOR 20.0f
#define VEL_SOLDADORASO 20.0f
#define VEL_SOLDADOENTRENADO 20.0f
#define VEL_TANQUE 20.0f
#define VEL_TANQUEPESADO 20.0f

#define FULL_LIFE_BASE 500
#define FULL_LIFE_BARRACA 300
#define FULL_LIFE_TORRETA 100
#define FULL_LIFE_RECOLECTOR 15
#define FULL_LIFE_SOLDADORASO 25
#define FULL_LIFE_SOLDADOENTRENADO 40
#define FULL_LIFE_TANQUE 80
#define FULL_LIFE_TANQUEPESADO 150

#define RADIO_MINERAL 4.0f
#define RADIO_BASE 15.0f
#define RADIO_BARRACA 12.0f
#define RADIO_TORRETA 5.0f
#define RADIO_RECOLECTOR 3.0f
#define RADIO_SOLDADORASO 3.0f
#define RADIO_SOLDADOENTRENADO 5.0f
#define RADIO_TANQUE 6.0f
#define RADIO_TANQUEPESADO 8.0f




#define CLOSE_ENTER_HUMAN_PLAYERS_SEC (6*60)
#define CLOSE_ENTER_IA_PLAYERS_SEC (7*60)
#define START_TO_CLOSE_SEC (10*60)



#define SPEED_CLOSE_AREA 10
#define TIME_WAIT_BEFORE_TO_AREA_CLOSE 40000
#define TIME_TO_UPDATE_AREA 5000

#define USE_PNG_MINIMAP true

#define SLEEP_THREAD_USER_READ_SOCK 10
#define SLEEP_THREAD_MAIN 100
#define MAX_OBJECTS_UPDATE_VIEW 500
#define TIMEOUT_CONNECT_TO_SERVER_MS 5000

#define MAX_BYTES_MINIMAP 250000

#define MAX_BYTES_SAVED_MAP 30000000

#define MAX_SIZE_NET_MESSAGE 10000


// Data base info
#define DATABASE_USER "biggestwaruser"
#define DATABASE_PASSWORD "biggestwarpass"
#define DATABASE_NAME "biggestwar"
#define DATABASE_HOST "127.0.0.1"
#define DATABASE_PORT 5400


// RL config (used by mainAdmin)
#define PATH_TO_AGENT "../RL/agentProg"
#define AMOUNT_PLAYERS_BY_EQUIPS_AT_LEAST (MAX_PLAYERS_BY_EQUIP-47)



